version: "3.8"

services:
  app:
    image: contactconx/conx-server:${IMAGE_TAG}
    ports:
      - "80:8080"
    restart: unless-stopped
    env_file:
      - .env

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 3s
      retries: 5